/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.extra.*;
import interfaz.Jugadores;
import interfaz.Menu;
import interfaz.Preguntas;
import interfaz.clasesAuxiliares.AnimatorSwing;
import interfaz.clasesAuxiliares.FadeOverlay;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JViewport;



/**
 *
 * @author hexal
 */
public class Configuracion extends javax.swing.JFrame {

    private JLabel blackScreen;
    
    /**
     * Creates new form PrePartida
     */
    public Configuracion() {
        initComponents();
        botonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AnimatorSwing.floatAnimation(fondo, 6, 0.01);

          // Fade de entrada al abrir la aplicación
         FadeOverlay overlay = new FadeOverlay(5, 20, Color.WHITE, () -> {
             // Esto se ejecuta cuando termina el fade
             System.out.println("Fade completado!");
         });
         getLayeredPane().add(overlay, JLayeredPane.MODAL_LAYER);
         overlay.setBounds(0, 0, getWidth(), getHeight());
         overlay.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editarJugadores = new javax.swing.JButton();
        editarCategorias = new javax.swing.JButton();
        editarPreguntas = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jugarText = new javax.swing.JLabel();
        jugarbase = new javax.swing.JLabel();
        jugarsombra = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        jugarText1 = new javax.swing.JLabel();
        jugarbase1 = new javax.swing.JLabel();
        jugarsombra1 = new javax.swing.JLabel();
        jugar1 = new javax.swing.JLabel();
        jugarText2 = new javax.swing.JLabel();
        jugarbase2 = new javax.swing.JLabel();
        jugarsombra2 = new javax.swing.JLabel();
        jugar2 = new javax.swing.JLabel();
        exitBo1 = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        menuTextBase = new javax.swing.JLabel();
        menuTextShadow = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarJugadores.setBorderPainted(false);
        editarJugadores.setContentAreaFilled(false);
        editarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarJugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(editarJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 320, 120));

        editarCategorias.setBorderPainted(false);
        editarCategorias.setContentAreaFilled(false);
        editarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCategoriasActionPerformed(evt);
            }
        });
        jPanel1.add(editarCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 320, 120));

        editarPreguntas.setBorderPainted(false);
        editarPreguntas.setContentAreaFilled(false);
        editarPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPreguntasActionPerformed(evt);
            }
        });
        jPanel1.add(editarPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 630, 320, 120));

        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 120));

        jugarText.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarText.setForeground(new java.awt.Color(255, 255, 255));
        jugarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText.setText("jugadores");
        jPanel1.add(jugarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 290, 70));

        jugarbase.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarbase.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase.setText("jugadores");
        jPanel1.add(jugarbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 290, 90));

        jugarsombra.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        jugarsombra.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra.setText("jugadores");
        jPanel1.add(jugarsombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 340, 80));

        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 730, 170));

        jugarText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarText1.setForeground(new java.awt.Color(255, 255, 255));
        jugarText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText1.setText("categorias");
        jPanel1.add(jugarText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 310, 80));

        jugarbase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarbase1.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase1.setText("categorias");
        jPanel1.add(jugarbase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 310, 100));

        jugarsombra1.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarsombra1.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra1.setText("categorias");
        jPanel1.add(jugarsombra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 360, 90));

        jugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 730, 170));

        jugarText2.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarText2.setForeground(new java.awt.Color(255, 255, 255));
        jugarText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText2.setText("preguntas");
        jPanel1.add(jugarText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 310, 80));

        jugarbase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarbase2.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase2.setText("preguntas");
        jPanel1.add(jugarbase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 310, 100));

        jugarsombra2.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarsombra2.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra2.setText("preguntas");
        jPanel1.add(jugarsombra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 640, 360, 90));

        jugar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 730, 170));

        exitBo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/exitBtnBigger.png"))); // NOI18N
        jPanel1.add(exitBo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 110));

        menuText.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText.setText("EDICION");
        jPanel1.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 800, 190));

        menuTextBase.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuTextBase.setForeground(new java.awt.Color(102, 102, 102));
        menuTextBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase.setText("EDICION");
        jPanel1.add(menuTextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 800, 260));

        menuTextShadow.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuTextShadow.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow.setText("EDICION");
        jPanel1.add(menuTextShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 930, 270));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/FA_1.png"))); // NOI18N
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 1440, 990));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/EnJuego.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Menu entrada = new Menu();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void editarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCategoriasActionPerformed
        Categorias entrada = new Categorias();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editarCategoriasActionPerformed

    private void editarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJugadoresActionPerformed
        Jugadores entrada = new Jugadores();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editarJugadoresActionPerformed

    private void editarPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPreguntasActionPerformed
        Preguntas entrada = new Preguntas();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editarPreguntasActionPerformed
 // SI ES CORRECTA O NO CORRECTA AÑADIR UN JOPTION PANE QUE DIGA SI ES CORRECTA O INCORRECTA LA OPCION
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton editarCategorias;
    private javax.swing.JButton editarJugadores;
    private javax.swing.JButton editarPreguntas;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exitBo1;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jugar;
    private javax.swing.JLabel jugar1;
    private javax.swing.JLabel jugar2;
    private javax.swing.JLabel jugarText;
    private javax.swing.JLabel jugarText1;
    private javax.swing.JLabel jugarText2;
    private javax.swing.JLabel jugarbase;
    private javax.swing.JLabel jugarbase1;
    private javax.swing.JLabel jugarbase2;
    private javax.swing.JLabel jugarsombra;
    private javax.swing.JLabel jugarsombra1;
    private javax.swing.JLabel jugarsombra2;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel menuTextBase;
    private javax.swing.JLabel menuTextShadow;
    // End of variables declaration//GEN-END:variables
}
