/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.clasesAuxiliares.AnimatorSwing;
import interfaz.clasesAuxiliares.FadeOverlay;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JLayeredPane;
import javax.swing.JViewport;
import logica.Categoria;
import logica.Juego;
import logica.Jugador;
import logica.PartidaLogica;
import logica.Pregunta;
import persistencia.Excepciones;
import persistencia.Respaldo;
import persistencia.Serializador;

/**
 *
 * @author hexal
 */
public class Partida extends javax.swing.JFrame {
    private PartidaLogica partida;
    private Juego juego; 
    /**
     * Creates new form PrePartida
     */
    public Partida(PartidaLogica partida) throws ClassNotFoundException, Excepciones {
        initComponents();
        juego = Juego.getInstance();
        this.partida = partida;
        
        botonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AnimatorSwing.floatAnimation(fondo, 6, 0.01);
        miTextArea.setOpaque(false);
        miTextArea.setBackground(new Color(0, 0, 0, 0)); // Totalmente transparente
        miTextArea.setBorder(BorderFactory.createEmptyBorder()); // Sin bordes
        miTextArea.setEditable(false); // Solo lectura
        miTextArea1.setOpaque(false);
        miTextArea1.setBackground(new Color(0, 0, 0, 0)); // Totalmente transparente
        miTextArea1.setBorder(BorderFactory.createEmptyBorder()); // Sin bordes
        miTextArea1.setEditable(false); // Solo lectura
        miTextArea2.setOpaque(false);
        miTextArea2.setBackground(new Color(0, 0, 0, 0)); // Totalmente transparente
        miTextArea2.setBorder(BorderFactory.createEmptyBorder()); // Sin bordes
        miTextArea2.setEditable(false); // Solo lectura
               miTextArea3.setOpaque(false);
        miTextArea3.setBackground(new Color(0, 0, 0, 0)); // Totalmente transparente
        miTextArea3.setBorder(BorderFactory.createEmptyBorder()); // Sin bordes
        miTextArea3.setEditable(false); // Solo lectura
                   miTextArea4.setOpaque(false);
        miTextArea4.setBackground(new Color(0, 0, 0, 0)); // Totalmente transparente
        miTextArea4.setBorder(BorderFactory.createEmptyBorder()); // Sin bordes
        miTextArea4.setEditable(false); // Solo lectura
        
        // Fade de entrada al abrir la aplicación
         FadeOverlay overlay = new FadeOverlay(10, 10, Color.WHITE, () -> {
             // Esto se ejecuta cuando termina el fade
             System.out.println("Fade completado!");
         });
         getLayeredPane().add(overlay, JLayeredPane.MODAL_LAYER);
         overlay.setBounds(0, 0, getWidth(), getHeight());
         overlay.start();
        
        
        


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        miTextArea = new javax.swing.JTextField();
        miTextArea1 = new javax.swing.JTextField();
        miTextArea2 = new javax.swing.JTextField();
        miTextArea3 = new javax.swing.JTextField();
        miTextArea4 = new javax.swing.JTextField();
        botonRespuesta1 = new javax.swing.JButton();
        botonRespuesta2 = new javax.swing.JButton();
        botonRespuesta3 = new javax.swing.JButton();
        botonRespuesta4 = new javax.swing.JButton();
        exitBo = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        menuTextBase = new javax.swing.JLabel();
        menuTextShadow = new javax.swing.JLabel();
        ursText1 = new javax.swing.JLabel();
        usrTextBase1 = new javax.swing.JLabel();
        usrTextShadow1 = new javax.swing.JLabel();
        catText1 = new javax.swing.JLabel();
        catTextBase1 = new javax.swing.JLabel();
        catTextShadow1 = new javax.swing.JLabel();
        tCatText2 = new javax.swing.JLabel();
        tCatTextBase2 = new javax.swing.JLabel();
        tCatTextShadow2 = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        rondaBase2 = new javax.swing.JLabel();
        rondaShadow2 = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        puntosBase = new javax.swing.JLabel();
        puntosShadow = new javax.swing.JLabel();
        triviaRespuesta2 = new javax.swing.JLabel();
        triviaRespuesta3 = new javax.swing.JLabel();
        Pregunta = new javax.swing.JLabel();
        triviaRespuesta5 = new javax.swing.JLabel();
        triviaRespuesta6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 120));

        miTextArea.setEditable(false);
        miTextArea.setBackground(new java.awt.Color(60, 59, 64));
        miTextArea.setFont(new java.awt.Font("Pixeloid Sans", 1, 24)); // NOI18N
        miTextArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miTextArea.setBorder(null);
        miTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTextAreaActionPerformed(evt);
            }
        });
        jPanel1.add(miTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 1010, 180));

        miTextArea1.setEditable(false);
        miTextArea1.setBackground(new java.awt.Color(60, 59, 64));
        miTextArea1.setFont(new java.awt.Font("Pixeloid Sans", 1, 14)); // NOI18N
        miTextArea1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miTextArea1.setBorder(null);
        miTextArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTextArea1ActionPerformed(evt);
            }
        });
        jPanel1.add(miTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 910, 260, 80));

        miTextArea2.setEditable(false);
        miTextArea2.setBackground(new java.awt.Color(60, 59, 64));
        miTextArea2.setFont(new java.awt.Font("Pixeloid Sans", 1, 14)); // NOI18N
        miTextArea2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miTextArea2.setBorder(null);
        miTextArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTextArea2ActionPerformed(evt);
            }
        });
        jPanel1.add(miTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 910, 260, 80));

        miTextArea3.setEditable(false);
        miTextArea3.setBackground(new java.awt.Color(60, 59, 64));
        miTextArea3.setFont(new java.awt.Font("Pixeloid Sans", 1, 14)); // NOI18N
        miTextArea3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miTextArea3.setBorder(null);
        miTextArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTextArea3ActionPerformed(evt);
            }
        });
        jPanel1.add(miTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 690, 260, 80));

        miTextArea4.setEditable(false);
        miTextArea4.setBackground(new java.awt.Color(60, 59, 64));
        miTextArea4.setFont(new java.awt.Font("Pixeloid Sans", 1, 14)); // NOI18N
        miTextArea4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miTextArea4.setBorder(null);
        miTextArea4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTextArea4ActionPerformed(evt);
            }
        });
        jPanel1.add(miTextArea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 690, 260, 80));

        botonRespuesta1.setBorderPainted(false);
        botonRespuesta1.setContentAreaFilled(false);
        botonRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespuesta1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 300, 120));

        botonRespuesta2.setBorderPainted(false);
        botonRespuesta2.setContentAreaFilled(false);
        botonRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespuesta2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 880, 300, 120));

        botonRespuesta3.setBorderPainted(false);
        botonRespuesta3.setContentAreaFilled(false);
        botonRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespuesta3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 670, 310, 120));

        botonRespuesta4.setBorderPainted(false);
        botonRespuesta4.setContentAreaFilled(false);
        botonRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespuesta4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonRespuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 880, 320, 120));

        exitBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/exitBtnBigger.png"))); // NOI18N
        jPanel1.add(exitBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 110));

        menuText.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText.setText("TURNO :");
        jPanel1.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -20, 800, 190));

        menuTextBase.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuTextBase.setForeground(new java.awt.Color(153, 153, 153));
        menuTextBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase.setText("TURNO :");
        jPanel1.add(menuTextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -50, 800, 260));

        menuTextShadow.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuTextShadow.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow.setText("TURNO :");
        jPanel1.add(menuTextShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -50, 930, 270));

        ursText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        ursText1.setForeground(new java.awt.Color(255, 255, 255));
        ursText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ursText1.setText("*USUARIO*");
        jPanel1.add(ursText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, -20, 800, 190));

        usrTextBase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextBase1.setForeground(new java.awt.Color(153, 153, 153));
        usrTextBase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextBase1.setText("*USUARIO*");
        jPanel1.add(usrTextBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, -50, 800, 260));

        usrTextShadow1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextShadow1.setForeground(new java.awt.Color(59, 113, 118));
        usrTextShadow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextShadow1.setText("*USUARIO*");
        jPanel1.add(usrTextShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, -50, 930, 270));

        catText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        catText1.setForeground(new java.awt.Color(255, 255, 255));
        catText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catText1.setText("CATEGORIA:");
        jPanel1.add(catText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 800, 190));

        catTextBase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        catTextBase1.setForeground(new java.awt.Color(153, 153, 153));
        catTextBase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catTextBase1.setText("CATEGORIA:");
        jPanel1.add(catTextBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 800, 260));

        catTextShadow1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        catTextShadow1.setForeground(new java.awt.Color(59, 113, 118));
        catTextShadow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catTextShadow1.setText("CATEGORIA:");
        jPanel1.add(catTextShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 930, 270));

        tCatText2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        tCatText2.setForeground(new java.awt.Color(255, 255, 255));
        tCatText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tCatText2.setText("*CATEGORIA*");
        jPanel1.add(tCatText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 800, 190));

        tCatTextBase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        tCatTextBase2.setForeground(new java.awt.Color(153, 153, 153));
        tCatTextBase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tCatTextBase2.setText("*CATEGORIA*");
        jPanel1.add(tCatTextBase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 800, 260));

        tCatTextShadow2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        tCatTextShadow2.setForeground(new java.awt.Color(59, 113, 118));
        tCatTextShadow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tCatTextShadow2.setText("*CATEGORIA*");
        jPanel1.add(tCatTextShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 930, 270));

        ronda.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        ronda.setForeground(new java.awt.Color(255, 255, 255));
        ronda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ronda.setText("1");
        jPanel1.add(ronda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, -50, 800, 190));

        rondaBase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        rondaBase2.setForeground(new java.awt.Color(153, 153, 153));
        rondaBase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rondaBase2.setText("1");
        jPanel1.add(rondaBase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, -80, 800, 260));

        rondaShadow2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        rondaShadow2.setForeground(new java.awt.Color(59, 113, 118));
        rondaShadow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rondaShadow2.setText("1");
        jPanel1.add(rondaShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, -80, 930, 270));

        puntos.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntos.setForeground(new java.awt.Color(255, 255, 255));
        puntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos.setText("0");
        jPanel1.add(puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 840, 800, 130));

        puntosBase.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosBase.setForeground(new java.awt.Color(153, 153, 153));
        puntosBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosBase.setText("0");
        jPanel1.add(puntosBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 810, 800, 200));

        puntosShadow.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosShadow.setForeground(new java.awt.Color(59, 113, 118));
        puntosShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosShadow.setText("0");
        jPanel1.add(puntosShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 810, 930, 210));

        triviaRespuesta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        triviaRespuesta2.setText("asdad");
        jPanel1.add(triviaRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 830, 680, 190));

        triviaRespuesta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(triviaRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 680, 190));

        Pregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Pregunta.png"))); // NOI18N
        jPanel1.add(Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1580, 550));

        triviaRespuesta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        triviaRespuesta5.setText("asdad");
        jPanel1.add(triviaRespuesta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 830, 680, 190));

        triviaRespuesta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        triviaRespuesta6.setText("asdad");
        jPanel1.add(triviaRespuesta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 680, 190));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Partida.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        try {
            Menu entrada = new Menu();
            entrada.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            System.getLogger(Partida.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (Excepciones ex) {
            System.getLogger(Partida.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
    }//GEN-LAST:event_botonSalirActionPerformed
 // SI ES CORRECTA O NO CORRECTA AÑADIR UN JOPTION PANE QUE DIGA SI ES CORRECTA O INCORRECTA LA OPCION
    
    private void miTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miTextAreaActionPerformed

    private void miTextArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTextArea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miTextArea1ActionPerformed

    private void miTextArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTextArea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miTextArea2ActionPerformed

    private void miTextArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTextArea3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miTextArea3ActionPerformed

    private void miTextArea4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTextArea4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miTextArea4ActionPerformed

    private void botonRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRespuesta1ActionPerformed

    private void botonRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRespuesta2ActionPerformed

    private void botonRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespuesta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRespuesta3ActionPerformed

    private void botonRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespuesta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRespuesta4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        PartidaLogica partida = new PartidaLogica();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Partida(partida).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    System.getLogger(Partida.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                } catch (Excepciones ex) {
                    System.getLogger(Partida.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pregunta;
    private javax.swing.JButton botonRespuesta1;
    private javax.swing.JButton botonRespuesta2;
    private javax.swing.JButton botonRespuesta3;
    private javax.swing.JButton botonRespuesta4;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel catText1;
    private javax.swing.JLabel catTextBase1;
    private javax.swing.JLabel catTextShadow1;
    private javax.swing.JLabel exitBo;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel menuTextBase;
    private javax.swing.JLabel menuTextShadow;
    private javax.swing.JTextField miTextArea;
    private javax.swing.JTextField miTextArea1;
    private javax.swing.JTextField miTextArea2;
    private javax.swing.JTextField miTextArea3;
    private javax.swing.JTextField miTextArea4;
    private javax.swing.JLabel puntos;
    private javax.swing.JLabel puntosBase;
    private javax.swing.JLabel puntosShadow;
    private javax.swing.JLabel ronda;
    private javax.swing.JLabel rondaBase2;
    private javax.swing.JLabel rondaShadow2;
    private javax.swing.JLabel tCatText2;
    private javax.swing.JLabel tCatTextBase2;
    private javax.swing.JLabel tCatTextShadow2;
    private javax.swing.JLabel triviaRespuesta2;
    private javax.swing.JLabel triviaRespuesta3;
    private javax.swing.JLabel triviaRespuesta5;
    private javax.swing.JLabel triviaRespuesta6;
    private javax.swing.JLabel ursText1;
    private javax.swing.JLabel usrTextBase1;
    private javax.swing.JLabel usrTextShadow1;
    // End of variables declaration//GEN-END:variables
}
