/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.clasesAuxiliares.AnimatorSwing;
import interfaz.clasesAuxiliares.FadeOverlay;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JViewport;



/**
 *
 * @author hexal
 */
public class Preguntas extends javax.swing.JFrame {

    private JLabel blackScreen;
    
    /**
     * Creates new form PrePartida
     */
    public Preguntas() {
        initComponents();
        botonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AnimatorSwing.floatAnimation(fondo, 6, 0.01);

          // Fade de entrada al abrir la aplicación
         FadeOverlay overlay = new FadeOverlay(5, 20, Color.WHITE, () -> {
             // Esto se ejecuta cuando termina el fade
             System.out.println("Fade completado!");
         });
         getLayeredPane().add(overlay, JLayeredPane.MODAL_LAYER);
         overlay.setBounds(0, 0, getWidth(), getHeight());
         overlay.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        añadirPre = new javax.swing.JButton();
        modPre = new javax.swing.JButton();
        borrarPre = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        listaCat = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jugarText1 = new javax.swing.JLabel();
        jugarbase1 = new javax.swing.JLabel();
        jugarsombra1 = new javax.swing.JLabel();
        jugar1 = new javax.swing.JLabel();
        menuText1 = new javax.swing.JLabel();
        configMenu = new javax.swing.JLabel();
        exitBo1 = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        menuTextBase = new javax.swing.JLabel();
        menuTextShadow = new javax.swing.JLabel();
        jugarText2 = new javax.swing.JLabel();
        jugarbase2 = new javax.swing.JLabel();
        jugarsombra2 = new javax.swing.JLabel();
        jugar2 = new javax.swing.JLabel();
        jugarText3 = new javax.swing.JLabel();
        jugarsombra3 = new javax.swing.JLabel();
        jugarbase3 = new javax.swing.JLabel();
        jugar3 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 120));

        añadirPre.setBorderPainted(false);
        añadirPre.setContentAreaFilled(false);
        añadirPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirPreActionPerformed(evt);
            }
        });
        jPanel1.add(añadirPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 320, 120));

        modPre.setBorderPainted(false);
        modPre.setContentAreaFilled(false);
        modPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPreActionPerformed(evt);
            }
        });
        jPanel1.add(modPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 320, 120));

        borrarPre.setBorderPainted(false);
        borrarPre.setContentAreaFilled(false);
        borrarPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPreActionPerformed(evt);
            }
        });
        jPanel1.add(borrarPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 320, 120));

        jComboBox1.setBackground(new java.awt.Color(7, 88, 119));
        jComboBox1.setFont(new java.awt.Font("Pixeloid Sans", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total", "Histroia", "informatica", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 300, 130, 40));

        jList1.setBackground(new java.awt.Color(7, 88, 119));
        jList1.setFont(new java.awt.Font("Pixeloid Sans", 1, 36)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Historia", "Matematica", "Informatica", "cultura" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setAutoscrolls(false);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jList1.setVisibleRowCount(4);
        listaCat.setViewportView(jList1);

        jPanel1.add(listaCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 430, 200));

        jugarText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarText1.setForeground(new java.awt.Color(255, 255, 255));
        jugarText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText1.setText("añadir");
        jPanel1.add(jugarText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 310, 80));

        jugarbase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarbase1.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase1.setText("añadir");
        jPanel1.add(jugarbase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 310, 100));

        jugarsombra1.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarsombra1.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra1.setText("añadir");
        jPanel1.add(jugarsombra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 360, 90));

        jugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 730, 170));

        menuText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        menuText1.setForeground(new java.awt.Color(255, 255, 255));
        menuText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText1.setText("PREGUNTAS");
        jPanel1.add(menuText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 800, 190));

        configMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/MenuSmall.png"))); // NOI18N
        jPanel1.add(configMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 1240, 570));

        exitBo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/exitBtnBigger.png"))); // NOI18N
        jPanel1.add(exitBo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 110));

        menuText.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText.setText("PREGUNTAS");
        jPanel1.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 800, 190));

        menuTextBase.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuTextBase.setForeground(new java.awt.Color(102, 102, 102));
        menuTextBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase.setText("PREGUNTAS");
        jPanel1.add(menuTextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 800, 260));

        menuTextShadow.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuTextShadow.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow.setText("PREGUNTAS");
        jPanel1.add(menuTextShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 930, 270));

        jugarText2.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarText2.setForeground(new java.awt.Color(255, 255, 255));
        jugarText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText2.setText("modificar");
        jPanel1.add(jugarText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 310, 80));

        jugarbase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarbase2.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase2.setText("modificar");
        jPanel1.add(jugarbase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 310, 100));

        jugarsombra2.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarsombra2.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra2.setText("modificar");
        jPanel1.add(jugarsombra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 360, 90));

        jugar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 730, 170));

        jugarText3.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarText3.setForeground(new java.awt.Color(255, 255, 255));
        jugarText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText3.setText("borrar");
        jPanel1.add(jugarText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 310, 80));

        jugarsombra3.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarsombra3.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra3.setText("borrar");
        jPanel1.add(jugarsombra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 360, 90));

        jugarbase3.setFont(new java.awt.Font("Pixeloid Sans", 0, 46)); // NOI18N
        jugarbase3.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase3.setText("borrar");
        jPanel1.add(jugarbase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 310, 100));

        jugar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 730, 170));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/FA_1.png"))); // NOI18N
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 1430, 990));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/EnJuego.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Menu entrada = new Menu();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void añadirPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirPreActionPerformed
        añadirPre entrada = new añadirPre();
        entrada.setVisible(true);
    }//GEN-LAST:event_añadirPreActionPerformed

    private void modPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPreActionPerformed
      modPre entrada = new modPre();
      entrada.setVisible(true);
    }//GEN-LAST:event_modPreActionPerformed

    private void borrarPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarPreActionPerformed
 // SI ES CORRECTA O NO CORRECTA AÑADIR UN JOPTION PANE QUE DIGA SI ES CORRECTA O INCORRECTA LA OPCION
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirPre;
    private javax.swing.JButton borrarPre;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel configMenu;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exitBo1;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jugar1;
    private javax.swing.JLabel jugar2;
    private javax.swing.JLabel jugar3;
    private javax.swing.JLabel jugarText1;
    private javax.swing.JLabel jugarText2;
    private javax.swing.JLabel jugarText3;
    private javax.swing.JLabel jugarbase1;
    private javax.swing.JLabel jugarbase2;
    private javax.swing.JLabel jugarbase3;
    private javax.swing.JLabel jugarsombra1;
    private javax.swing.JLabel jugarsombra2;
    private javax.swing.JLabel jugarsombra3;
    private javax.swing.JScrollPane listaCat;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel menuText1;
    private javax.swing.JLabel menuTextBase;
    private javax.swing.JLabel menuTextShadow;
    private javax.swing.JButton modPre;
    // End of variables declaration//GEN-END:variables
}
