/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.clasesAuxiliares.AnimatorSwing;
import interfaz.clasesAuxiliares.FadeOverlay;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JViewport;



/**
 *
 * @author hexal
 */
public class Resultados extends javax.swing.JFrame {

    private JLabel blackScreen;
    
    /**
     * Creates new form PrePartida
     */
    public Resultados() {
        initComponents();
        botonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AnimatorSwing.floatAnimation(fondo, 6, 0.01);
        AnimatorSwing.floatAnimation(cup, 5, 0.06);
        
          // Fade de entrada al abrir la aplicación
         FadeOverlay overlay = new FadeOverlay(90, 100, Color.WHITE, () -> {
             // Esto se ejecuta cuando termina el fade
             System.out.println("Fade completado!");
         });
         getLayeredPane().add(overlay, JLayeredPane.MODAL_LAYER);
         overlay.setBounds(0, 0, getWidth(), getHeight());
         overlay.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonSalir1 = new javax.swing.JButton();
        jugarlbl2 = new javax.swing.JLabel();
        jugarbase2 = new javax.swing.JLabel();
        jugarsombra2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        puntosBase = new javax.swing.JLabel();
        puntosShadow = new javax.swing.JLabel();
        puntos2 = new javax.swing.JLabel();
        puntosBase2 = new javax.swing.JLabel();
        puntosShadow2 = new javax.swing.JLabel();
        puntos4 = new javax.swing.JLabel();
        puntosBase4 = new javax.swing.JLabel();
        puntosShadow4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exitBo1 = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        menuTextBase = new javax.swing.JLabel();
        menuTextShadow = new javax.swing.JLabel();
        ursText1 = new javax.swing.JLabel();
        usrTextBase1 = new javax.swing.JLabel();
        usrTextShadow1 = new javax.swing.JLabel();
        ursText2 = new javax.swing.JLabel();
        usrTextBase2 = new javax.swing.JLabel();
        usrTextShadow2 = new javax.swing.JLabel();
        ursText3 = new javax.swing.JLabel();
        usrTextBase3 = new javax.swing.JLabel();
        usrTextShadow3 = new javax.swing.JLabel();
        cup = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        puntosShadow1 = new javax.swing.JLabel();
        puntos1 = new javax.swing.JLabel();
        puntosBase1 = new javax.swing.JLabel();
        puntosShadow3 = new javax.swing.JLabel();
        puntosBase3 = new javax.swing.JLabel();
        puntos3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 120));

        botonSalir1.setBorderPainted(false);
        botonSalir1.setContentAreaFilled(false);
        botonSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        botonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 830, 360, 130));

        jugarlbl2.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarlbl2.setForeground(new java.awt.Color(255, 255, 255));
        jugarlbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarlbl2.setText("VOLVER");
        jPanel1.add(jugarlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 860, 200, 70));

        jugarbase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarbase2.setForeground(new java.awt.Color(153, 0, 153));
        jugarbase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase2.setText("VOLVER");
        jPanel1.add(jugarbase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 860, 200, 90));

        jugarsombra2.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        jugarsombra2.setForeground(new java.awt.Color(92, 71, 125));
        jugarsombra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra2.setText("VOLVER");
        jPanel1.add(jugarsombra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 860, 250, 80));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/EXIT.png"))); // NOI18N
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 790, 730, 170));

        puntos.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntos.setForeground(new java.awt.Color(255, 255, 255));
        puntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos.setText("0");
        jPanel1.add(puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 800, 130));

        puntosBase.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosBase.setForeground(new java.awt.Color(153, 153, 153));
        puntosBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosBase.setText("0");
        jPanel1.add(puntosBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 800, 200));

        puntosShadow.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosShadow.setForeground(new java.awt.Color(59, 113, 118));
        puntosShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosShadow.setText("0");
        jPanel1.add(puntosShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 930, 210));

        puntos2.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntos2.setForeground(new java.awt.Color(255, 255, 255));
        puntos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos2.setText("0");
        jPanel1.add(puntos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 800, 130));

        puntosBase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosBase2.setForeground(new java.awt.Color(153, 153, 153));
        puntosBase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosBase2.setText("0");
        jPanel1.add(puntosBase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 800, 200));

        puntosShadow2.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosShadow2.setForeground(new java.awt.Color(59, 113, 118));
        puntosShadow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosShadow2.setText("0");
        jPanel1.add(puntosShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 930, 210));

        puntos4.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntos4.setForeground(new java.awt.Color(255, 255, 255));
        puntos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos4.setText("0");
        jPanel1.add(puntos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 650, 800, 130));

        puntosBase4.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosBase4.setForeground(new java.awt.Color(153, 153, 153));
        puntosBase4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosBase4.setText("0");
        jPanel1.add(puntosBase4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, 800, 200));

        puntosShadow4.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosShadow4.setForeground(new java.awt.Color(59, 113, 118));
        puntosShadow4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosShadow4.setText("0");
        jPanel1.add(puntosShadow4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 620, 930, 210));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 130, 310));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, 200));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 660, -1, 130));

        exitBo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/exitBtnBigger.png"))); // NOI18N
        jPanel1.add(exitBo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 110));

        menuText.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText.setText("RESULTADOS");
        jPanel1.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 800, 190));

        menuTextBase.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuTextBase.setForeground(new java.awt.Color(102, 102, 102));
        menuTextBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase.setText("RESULTADOS");
        jPanel1.add(menuTextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 800, 260));

        menuTextShadow.setFont(new java.awt.Font("Pixeloid Sans", 1, 100)); // NOI18N
        menuTextShadow.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow.setText("RESULTADOS");
        jPanel1.add(menuTextShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 930, 270));

        ursText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        ursText1.setForeground(new java.awt.Color(228, 228, 98));
        ursText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ursText1.setText("*USUARIO*");
        jPanel1.add(ursText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 800, 190));

        usrTextBase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextBase1.setForeground(new java.awt.Color(136, 136, 74));
        usrTextBase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextBase1.setText("*USUARIO*");
        jPanel1.add(usrTextBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 800, 260));

        usrTextShadow1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextShadow1.setForeground(new java.awt.Color(83, 83, 68));
        usrTextShadow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextShadow1.setText("*USUARIO*");
        jPanel1.add(usrTextShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 930, 270));

        ursText2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        ursText2.setForeground(new java.awt.Color(255, 255, 255));
        ursText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ursText2.setText("*USUARIO*");
        jPanel1.add(ursText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 800, 190));

        usrTextBase2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextBase2.setForeground(new java.awt.Color(153, 153, 153));
        usrTextBase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextBase2.setText("*USUARIO*");
        jPanel1.add(usrTextBase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 800, 260));

        usrTextShadow2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextShadow2.setForeground(new java.awt.Color(59, 113, 118));
        usrTextShadow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextShadow2.setText("*USUARIO*");
        jPanel1.add(usrTextShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 930, 270));

        ursText3.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        ursText3.setForeground(new java.awt.Color(142, 108, 8));
        ursText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ursText3.setText("*USUARIO*");
        jPanel1.add(ursText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 800, 190));

        usrTextBase3.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextBase3.setForeground(new java.awt.Color(118, 91, 11));
        usrTextBase3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextBase3.setText("*USUARIO*");
        jPanel1.add(usrTextBase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, 800, 260));

        usrTextShadow3.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        usrTextShadow3.setForeground(new java.awt.Color(128, 119, 95));
        usrTextShadow3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrTextShadow3.setText("*USUARIO*");
        jPanel1.add(usrTextShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 930, 270));

        cup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/diseno-trofeo-pixelado-pixel-golden-trophy-ganador-trofeo-copa-pixel-art-primer-lugar_709240-122_1.PNG"))); // NOI18N
        jPanel1.add(cup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 920, 470));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/EnJuego.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1920, 1080));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, -1, -1));

        puntosShadow1.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosShadow1.setForeground(new java.awt.Color(59, 113, 118));
        puntosShadow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosShadow1.setText("0");
        jPanel1.add(puntosShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 930, 210));

        puntos1.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntos1.setForeground(new java.awt.Color(255, 255, 255));
        puntos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos1.setText("0");
        jPanel1.add(puntos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 800, 130));

        puntosBase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosBase1.setForeground(new java.awt.Color(153, 153, 153));
        puntosBase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosBase1.setText("0");
        jPanel1.add(puntosBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 800, 200));

        puntosShadow3.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosShadow3.setForeground(new java.awt.Color(59, 113, 118));
        puntosShadow3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosShadow3.setText("0");
        jPanel1.add(puntosShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 550, 930, 210));

        puntosBase3.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntosBase3.setForeground(new java.awt.Color(153, 153, 153));
        puntosBase3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntosBase3.setText("0");
        jPanel1.add(puntosBase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 800, 200));

        puntos3.setFont(new java.awt.Font("Pixeloid Sans", 0, 100)); // NOI18N
        puntos3.setForeground(new java.awt.Color(255, 255, 255));
        puntos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntos3.setText("0");
        jPanel1.add(puntos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 800, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Menu entrada = new Menu();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir1ActionPerformed
        Menu entrada = new Menu();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalir1ActionPerformed
 // SI ES CORRECTA O NO CORRECTA AÑADIR UN JOPTION PANE QUE DIGA SI ES CORRECTA O INCORRECTA LA OPCION
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JLabel cup;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exitBo1;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jugarbase2;
    private javax.swing.JLabel jugarlbl2;
    private javax.swing.JLabel jugarsombra2;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel menuTextBase;
    private javax.swing.JLabel menuTextShadow;
    private javax.swing.JLabel puntos;
    private javax.swing.JLabel puntos1;
    private javax.swing.JLabel puntos2;
    private javax.swing.JLabel puntos3;
    private javax.swing.JLabel puntos4;
    private javax.swing.JLabel puntosBase;
    private javax.swing.JLabel puntosBase1;
    private javax.swing.JLabel puntosBase2;
    private javax.swing.JLabel puntosBase3;
    private javax.swing.JLabel puntosBase4;
    private javax.swing.JLabel puntosShadow;
    private javax.swing.JLabel puntosShadow1;
    private javax.swing.JLabel puntosShadow2;
    private javax.swing.JLabel puntosShadow3;
    private javax.swing.JLabel puntosShadow4;
    private javax.swing.JLabel ursText1;
    private javax.swing.JLabel ursText2;
    private javax.swing.JLabel ursText3;
    private javax.swing.JLabel usrTextBase1;
    private javax.swing.JLabel usrTextBase2;
    private javax.swing.JLabel usrTextBase3;
    private javax.swing.JLabel usrTextShadow1;
    private javax.swing.JLabel usrTextShadow2;
    private javax.swing.JLabel usrTextShadow3;
    // End of variables declaration//GEN-END:variables
}
